{{- range .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app: {{ .name }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        {{- range .containers }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}

          {{- with .command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- if and $.Values.configmap.enabled $.Values.configmap.mountPath }}
          volumeMounts:
            - name: {{ $.Values.configmap.volumeName | default "app-config" }}
              mountPath: {{ $.Values.configmap.mountPath }}
          {{- end }}
        {{- end }}

      {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if $.Values.configmap.enabled }}
      volumes:
        - name: {{ $.Values.configmap.volumeName | default "app-config" }}
          configMap:
            name: {{ include "generic.fullname" $ }}
      {{- end }}
{{- end }}
