{{- range .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app: {{ .name }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}

          {{- if .command }}
          command: {{ toYaml .command | nindent 10 }}
          {{- end }}

          {{- if .args }}
          args: {{ toYaml .args | nindent 10 }}
          {{- end }}

          ports:
            {{- range .ports }}
            - name: {{ .name | default "http" }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}

          {{- if .env }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}

          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}

          {{- if .volumeMounts }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          {{- end }}

          {{- if $.Values.configmap.enabled }}
          volumeMounts:
            - name: myapp-generic-chart
              mountPath: /etc/config
          {{- end }}

      {{- if .volumes }}
      volumes:
        {{- toYaml .volumes | nindent 8 }}
      {{- end }}

      {{- if $.Values.configmap.enabled }}
      volumes:
        - name: myapp-generic-chart
          configMap:
            name: {{ include "generic.fullname" $ }}
      {{- end }}

      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}
---
{{- end }}